name: material_app
description: A new Flutter project.
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  # PDF 相关
  file_picker: ^6.0.0
  path_provider: ^2.1.0
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # 启动图标生成工具（新增）
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/FangSong.ttf

# 启动图标配置（新增）
flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon_1024.png
  remove_alpha_ios: true
  min_sdk_android: 21
