name: material_app
description: A new Flutter project.
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  # PDF 相关
  pdf: ^3.10.4
  printing: ^5.11.0
  # 扫码相关
  mobile_scanner: ^5.0.0
  permission_handler: ^11.3.0
  # --- 新增：文件处理相关 ---
  file_picker: ^6.0.0
  path_provider: ^2.1.0
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/FangSong.ttf

flutter_launcher_icons:
  android: true      # 只给安卓生成图标；如果以后要给 iOS 也用，改成 true
  ios: false
  image_path_svg: assets/app_icon_desktop.svg