name: material_app
description: A new Flutter project.
publish_to: 'none'
version: 1.3.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.0.5
  # 本地存储
  shared_preferences: ^2.2.0
  # 图标库
  cupertino_icons: ^1.0.2
  # 日期格式化
  intl: ^0.18.1
  # PDF生成与打印
  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # --- 这里是新增的字体配置 ---
  assets:
    - assets/fonts/FangSong.ttf
